/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_companies_get"];
        put?: never;
        /** Create Company */
        post: operations["create_company_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/tech-stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tech Stacks */
        get: operations["list_tech_stacks_companies_tech_stacks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Stats */
        get: operations["get_company_stats_companies__company_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/salary-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Salary Submissions */
        get: operations["get_salary_submissions_companies__company_id__salary_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/interview-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview Submissions */
        get: operations["get_interview_submissions_companies__company_id__interview_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Salary Submission */
        post: operations["create_salary_submission_salary_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interview Submissions */
        get: operations["list_interview_submissions_interview_submissions_get"];
        put?: never;
        /** Create Interview Submission */
        post: operations["create_interview_submission_interview_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview-submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview Submission */
        get: operations["get_interview_submission_interview_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_articles__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/salary-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Salary */
        get: operations["list_all_salary_admin_salary_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/salary-submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Salary */
        delete: operations["delete_salary_admin_salary_submissions__submission_id__delete"];
        options?: never;
        head?: never;
        /** Update Salary */
        patch: operations["update_salary_admin_salary_submissions__submission_id__patch"];
        trace?: never;
    };
    "/admin/salary-submissions/{submission_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Salary */
        post: operations["approve_salary_admin_salary_submissions__submission_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/salary-submissions/{submission_id}/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unapprove Salary */
        post: operations["unapprove_salary_admin_salary_submissions__submission_id__unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/interview-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Interview */
        get: operations["list_all_interview_admin_interview_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/interview-submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Interview */
        delete: operations["delete_interview_admin_interview_submissions__submission_id__delete"];
        options?: never;
        head?: never;
        /** Update Interview */
        patch: operations["update_interview_admin_interview_submissions__submission_id__patch"];
        trace?: never;
    };
    "/admin/interview-submissions/{submission_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Interview */
        post: operations["approve_interview_admin_interview_submissions__submission_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/interview-submissions/{submission_id}/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unapprove Interview */
        post: operations["unapprove_interview_admin_interview_submissions__submission_id__unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Companies */
        get: operations["list_all_companies_admin_companies_get"];
        put?: never;
        /** Create Company Admin */
        post: operations["create_company_admin_admin_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Company */
        delete: operations["delete_company_admin_companies__company_id__delete"];
        options?: never;
        head?: never;
        /** Update Company */
        patch: operations["update_company_admin_companies__company_id__patch"];
        trace?: never;
    };
    "/admin/companies/{company_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Company */
        post: operations["approve_company_admin_companies__company_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_admin_articles_get"];
        put?: never;
        /** Create Article */
        post: operations["create_article_admin_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Article */
        delete: operations["delete_article_admin_articles__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_admin_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contacts/{contact_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Contact */
        post: operations["resolve_contact_admin_contacts__contact_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_admin_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Industries */
        get: operations["list_industries_industries_get"];
        put?: never;
        /** Create Industry */
        post: operations["create_industry_industries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/industries/{industry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Industry */
        delete: operations["delete_industry_industries__industry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Contact */
        post: operations["submit_contact_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global Stats */
        get: operations["global_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleCreate */
        ArticleCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Content */
            content?: string | null;
        };
        /** ArticleRead */
        ArticleRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Content */
            content?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompanyCreate */
        CompanyCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Industry */
            industry?: string | null;
            /** Employee Count */
            employee_count?: number | null;
            /** Founded Year */
            founded_year?: number | null;
            /** Headquarters */
            headquarters?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
        };
        /** CompanyRead */
        CompanyRead: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Industry */
            industry?: string | null;
            /** Employee Count */
            employee_count?: number | null;
            /** Founded Year */
            founded_year?: number | null;
            /** Headquarters */
            headquarters?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Id */
            id: number;
            /**
             * Is Approved
             * @default false
             */
            is_approved: boolean;
        };
        /** CompanyStats */
        CompanyStats: {
            /** Avg Salary */
            avg_salary?: number | null;
            /** Median Salary */
            median_salary?: number | null;
            /** Min Salary */
            min_salary?: number | null;
            /** Max Salary */
            max_salary?: number | null;
            /**
             * Submission Count
             * @default 0
             */
            submission_count: number;
        };
        /** CompanyUpdate */
        CompanyUpdate: {
            /** Name */
            name?: string | null;
            /** Industry */
            industry?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ContactCreate */
        ContactCreate: {
            /** Category */
            category: string;
            /** Email */
            email?: string | null;
            /** Message */
            message: string;
        };
        /** ContactRead */
        ContactRead: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Email */
            email?: string | null;
            /** Message */
            message: string;
            /** Is Resolved */
            is_resolved: boolean;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndustryCreate */
        IndustryCreate: {
            /** Name */
            name: string;
        };
        /** IndustryRead */
        IndustryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** InterviewSubmissionAdmin */
        InterviewSubmissionAdmin: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title?: string | null;
            /** Interview Rounds */
            interview_rounds?: number | null;
            /** Result */
            result?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Tags */
            tags?: string | null;
            /** Interview Content */
            interview_content?: string | null;
            /** Is Approved */
            is_approved: boolean;
            /** Created At */
            created_at: string;
        };
        /** InterviewSubmissionCreate */
        InterviewSubmissionCreate: {
            /** Company Id */
            company_id: number;
            /** Job Title */
            job_title?: string | null;
            /** Interview Rounds */
            interview_rounds: number;
            /** Result */
            result?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Tags */
            tags?: string | null;
            /** Interview Content */
            interview_content?: string | null;
        };
        /** InterviewSubmissionRead */
        InterviewSubmissionRead: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Job Title */
            job_title?: string | null;
            /** Interview Rounds */
            interview_rounds?: number | null;
            /** Result */
            result?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Tags */
            tags?: string | null;
            /** Interview Content */
            interview_content?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InterviewSubmissionUpdate */
        InterviewSubmissionUpdate: {
            /** Job Title */
            job_title?: string | null;
            /** Interview Rounds */
            interview_rounds?: number | null;
            /** Result */
            result?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Tags */
            tags?: string | null;
            /** Interview Content */
            interview_content?: string | null;
        };
        /** InterviewSubmissionWithCompany */
        InterviewSubmissionWithCompany: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Job Title */
            job_title?: string | null;
            /** Interview Rounds */
            interview_rounds?: number | null;
            /** Result */
            result?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Tags */
            tags?: string | null;
            /** Interview Content */
            interview_content?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company Name */
            company_name: string;
        };
        /** SalarySubmissionAdmin */
        SalarySubmissionAdmin: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /** Job Title */
            job_title?: string | null;
            /** Years Of Experience */
            years_of_experience?: number | null;
            /** Salary */
            salary?: number | null;
            /** Salary Breakdown */
            salary_breakdown?: string | null;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Overtime Feeling */
            overtime_feeling?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Comment */
            comment?: string | null;
            /** Is Approved */
            is_approved: boolean;
            /** Created At */
            created_at: string;
        };
        /** SalarySubmissionCreate */
        SalarySubmissionCreate: {
            /** Company Id */
            company_id: number;
            /** Job Title */
            job_title?: string | null;
            /** Years Of Experience */
            years_of_experience: number;
            /** Salary */
            salary: number;
            /** Salary Breakdown */
            salary_breakdown?: string | null;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Overtime Feeling */
            overtime_feeling?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** SalarySubmissionRead */
        SalarySubmissionRead: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Job Title */
            job_title?: string | null;
            /** Years Of Experience */
            years_of_experience?: number | null;
            /** Salary */
            salary?: number | null;
            /** Salary Breakdown */
            salary_breakdown?: string | null;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Overtime Feeling */
            overtime_feeling?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SalarySubmissionUpdate */
        SalarySubmissionUpdate: {
            /** Job Title */
            job_title?: string | null;
            /** Years Of Experience */
            years_of_experience?: number | null;
            /** Salary */
            salary?: number | null;
            /** Salary Breakdown */
            salary_breakdown?: string | null;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Overtime Feeling */
            overtime_feeling?: string | null;
            /** Tech Stack */
            tech_stack?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_companies_companies_get: {
        parameters: {
            query?: {
                search?: string | null;
                industry?: string | null;
                tech_stack?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tech_stacks_companies_tech_stacks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_company_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_stats_companies__company_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_salary_submissions_companies__company_id__salary_submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalarySubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_submissions_companies__company_id__interview_submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_salary_submission_salary_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalarySubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalarySubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interview_submissions_interview_submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSubmissionWithCompany"][];
                };
            };
        };
    };
    create_interview_submission_interview_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewSubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_submission_interview_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSubmissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_articles_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_articles__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_salary_admin_salary_submissions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalarySubmissionAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_salary_admin_salary_submissions__submission_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_salary_admin_salary_submissions__submission_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalarySubmissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_salary_admin_salary_submissions__submission_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_salary_admin_salary_submissions__submission_id__unapprove_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_interview_admin_interview_submissions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSubmissionAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interview_admin_interview_submissions__submission_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interview_admin_interview_submissions__submission_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewSubmissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_interview_admin_interview_submissions__submission_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_interview_admin_interview_submissions__submission_id__unapprove_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_companies_admin_companies_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_admin_admin_companies_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_admin_companies__company_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_admin_companies__company_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_company_admin_companies__company_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_admin_articles_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_admin_articles_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_admin_articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_admin_contacts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_contact_admin_contacts__contact_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_admin_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_industries_industries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryRead"][];
                };
            };
        };
    };
    create_industry_industries_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndustryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_industry_industries__industry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                industry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    submit_contact_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
